import { ColorModeScript } from "@chakra-ui/react";
import theme from "./theme";
import AppContainer from "@/components/AppContainer";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <AppContainer cookies={cookies().toString()}>{children}</AppContainer>
      </body>
    </html>
  );
}
